version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-omero-grid:
    image: openmicroscopy/omero-grid
    command: master
    container_name:  §§INSTANCE-omero-master
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-omero-db:db
    environment:
      DBHOST: omero-db
      DBUSER: omero
      DBPASS: §§POSTGRES_PASSWORD
      DBNAME: omero
      ROOTPASS: omero
    volumes_from: 
      - §§INSTANCE-omero-data

    depends_on:
      - §§INSTANCE-omero-db
      - §§INSTANCE-omero-data
   
  §§INSTANCE-omero-db:
    image: postgres
    container_name: §§INSTANCE-omero-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - POSTGRES_PASSWORD=§§POSTGRES_PASSWORD
      - POSTGRES_USER=xnat
      - POSTGRES_DB=xnat 
    volumes_from: 
      - §§INSTANCE-omero-data
    depends_on:
      - §§INSTANCE-omero-data


  §§INSTANCE-omero-web:
    image: openmicroscopy/omero-grid-web
    container_name: §§INSTANCE-omero-web
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      MASTER_ADDR: §§INSTANCE-omero-grid
    depends_on:
      - §§INSTANCE-omero-grid
    links:
      - §§INSTANCE-omero-grid:master
    ports:
      - "§§PORT:8080"


  §§INSTANCE-omero-data:
    image: busybox
    container_name: §§INSTANCE-omero-data
    volumes:
      - ./data/OMERO:/OMERO
      - ./data/postgres:/var/lib/postgresql/data
    command: "chown 1000:1000 /OMERO"
