version: "3.8"

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-omero-db:
    image: "postgres:11"
    restart: unless-stopped
    container_name: §§INSTANCE-omero-db
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: §§POSTGRES_PASSWORD
      networks:
      - bibbox-default-network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  §§INSTANCE-omero-server:
    image: "openmicroscopy/omero-server:5.6"
    restart: unless-stopped
    container_name: §§INSTANCE-omero-server
    environment:
      CONFIG_omero_db_host: §§INSTANCE-omero-db
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: §§POSTGRES_PASSWORD
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - bibbox-default-network
    ports:
      - "§§PORT3:4063"
      - "§§PORT2:4064"
    volumes:
      - ./data/omero:/OMERO
      - ./data/ome-server-var:/opt/omero/server/OMERO.server/var
      - /home/mupaadmin/test_data:/OMERO/share

  §§INSTANCE-omero-web:
    image: "openmicroscopy/omero-web-standalone:5.6"
    restart: unless-stopped
    environment:
      OMEROHOST: §§INSTANCE-omero-server
    networks:
      - bibbox-default-network
    ports:
      - "§§PORT1:4080"

