version: "3"
# hallo comment
networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-omero-db:
    image: "postgres:11"
    restart: unless-stopped
    container_name: §§INSTANCE-omero-db
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: §§POSTGRES_PASSWORD
    networks: 
      - bibbox-default-network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw

  §§INSTANCE-omero-server:
    image: "openmicroscopy/omero-server:5.6"
    restart: unless-stopped
    container_name: §§INSTANCE-omero-server
    environment:
      CONFIG_omero_db_host: §§INSTANCE-omero-db
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: §§POSTGRES_PASSWORD
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks: 
      - bibbox-default-network
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - ./data/OMERO:/OMERO
    command: chmod -R 777 && /tail -f /dev/null
  
  §§INSTANCE-omero-web:
    image: "openmicroscopy/omero-web-standalone:5.6"
    container_name: §§INSTANCE-omero-web
    restart: unless-stopped
    environment:
      OMEROHOST: §§INSTANCE-omero-server
    networks: 
      - bibbox-default-network
    proxy:
     TYPE: PRIMARY
     URLPREFIX:  §§INSTANCE
     TEMPLATE: default
     DISPLAYNAME: 'Omero'
    ports:
      - "4080:4080"
