version: '2'

      
services:

  dev-omero:
    image: openmicroscopy/omero-grid
    container_name:  dev-omero-master-local
    restart: unless-stopped
    links:
      - dev-omero-db
    ports:
      - "4063:4063"
      - "4064:4064"
    environment:   
      DBHOST: dev-omero-db
      DBUSER: postgres
      DBPASS: postgres
      DBNAME: postgres
      ROOTPASS: omero 
    depends_on:
      - dev-omero-db
      - dev-omero-data
    volumes_from: 
      - dev-omero-data

  dev-omero-db:
    image: postgres
    container_name: dev-omero-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres  
    volumes_from: 
      - dev-omero-data
    depends_on:
      - dev-omero-data

  dev-omero-web:
    image: openmicroscopy/omero-grid-web
    container_name: dev-omero-web
    restart: unless-stopped
    depends_on:
      - dev-omero
    links:
      - dev-omero:dev-omero-master-local
    ports:
      - "8080:8080"
   

  dev-omero-data:
    image: busybox
    container_name: dev-omero-data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/omero:/data/omero


